server:
  port: 8083

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://postgres/customer
    initialization-mode: always
    jpa:
      show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: notification_queue
  exchange:
    name: notification_exchange
  routing:
    key: notification_routing_key
  json:
    queue:
      name: json_notification_queue
    routing:
      key: json_notification_routing_key

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
