version: "3"
services:
  online_store_database:
    image: postgres:16.0
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online_store
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  online_store:
    build: ./online_store
    ports:
      - "8080:8080"
    depends_on:
      - online_store_database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://online_store_database:5432/online_store
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - postgres

  chatbot:
    build: ./chatbot
    ports:
      - "5000:5000"
    volumes:
      - chatbot:/data/chatbot

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  chatbot:
