server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/notification
    initialization-mode: always
    jpa:
      show-sql: true
  zipkin:
    base-url: http://localhost:9411

rabbitmq:
  queue:
    name: notification_queue
  exchange:
    name: notification_exchange
  routing:
    key: notification_routing_key
  json:
    queue:
      name: json_notification_queue
    routing:
      key: json_notification_routing_key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
