server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/notification
    initialization-mode: always
    jpa:
      show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
