version: '3.8'

services:
  postgres:
    image: 'postgres:16.0'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: film_db