server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'postgres'
    password: 'password'
    url: jdbc:postgresql://postgres/fraud
    initialization-mode: always
    jpa:
      show-sql: true
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
